### ISSUE TITLE
Criticas Construtivas!

### ISSUE THREAD

**Issue by JhoanDev** [classroom-ufersa/BuscaSequencialClientes#1]
1# Utilizar mais de uma branch para não haver commits direto na main, sugiro utilização do git flow, irei anexar o link : [sobre o git flow](https://www.atlassian.com/br/git/tutorials/comparing-workflows/gitflow-workflow)

2# sugiro que realizem testes em todas as funções .

3# Melhorem o readme, coloquem informações sobre o projeto e sobre o algoritimo de busca sequencial.

**Comment by JhoanDev** [comment]
@biiaalmeida @letsticia @alexrbss @hillaryds

**Comment by letsticia** [comment]
- 1# Como os outros membros ainda não tinham feito o curso de git, preferimos por não utilizar o Gitflow (já comunicado à professora), entretanto, adotaremos a prática nos próximos projetos.

- 2# Os testes serão feitos!

- 3# Foi adicionado o arquivo README.md para cada uma das linguagens a ser utilizada, assim como fora colocado um geral para explicar sobre o algoritmo de busca sequencial.

**Comment by JhoanDev** [comment]
Ótimo!
